"""OMLE Python SDK — open machine learning exchange format.

Quick start::

    from omle import OMLEModel, ModelMetadata, InputSpec, OutputSpec
    from omle import TensorType, DataType, OutputRole
    from omle import save, load, save_json, load_json, validate

    # Build a model
    model = OMLEModel(
        metadata=ModelMetadata(
            format_version="0.1.0",
            name="my_model",
            producer="my_tool",
            source_frameworks=[SourceFramework(name="scikit-learn")],
        ),
        inputs=[InputSpec(name="X", type=TensorType(dtype=DataType.FLOAT32, shape=[-1, 10]))],
        outputs=[OutputSpec(name="prediction", role=OutputRole.PREDICTION)],
    )

    # Validate
    result = validate(model)
    if not result.is_valid:
        print(result)

    # Save / load JSON
    save_json(model, "model.json")
    model2 = load_json("model.json")

    # Save / load protobuf (requires protobuf package + gen_proto.sh)
    save(model, "model.omle")
    model3 = load("model.omle")
"""

# IR types — flat re-export so users can do ``from omle import X``
# I/O
from .io import (
    from_json,
    from_proto_bytes,
    load,
    load_json,
    load_proto,
    save,
    save_json,
    save_proto,
    to_json,
    to_proto_bytes,
)
from .ir import (
    SVM,
    AnomalyDetection,
    Apply,
    Attribute,
    BernoulliNaiveBayes,
    BooleanOperator,
    CategoricalNaiveBayes,
    Clustering,
    ComplexPredicate,
    CompositeNode,
    CompoundPredicate,
    ContinuousDomain,
    CovarianceType,
    CSRMatrix,
    # enums
    DataType,
    # function
    DefineFunction,
    DenseLayer,
    DetectionMode,
    DiscreteDomain,
    DistanceMeasure,
    DomainValue,
    EllipticEnvelope,
    # expression
    Expression,
    FalsePredicate,
    Feature,
    FunctionParameter,
    GaussianMixtureClustering,
    GaussianNaiveBayes,
    # interface
    InputSpec,
    Interval,
    IntervalClosure,
    InvalidValuePolicy,
    IsolationForest,
    KernelSVM,
    # bodies
    Linear,
    LinearOneClassSVM,
    LinearSVM,
    LocalOutlierFactor,
    MeasureLevel,
    MissingValuePolicy,
    # metadata
    ModelMetadata,
    # schema
    ModelSchema,
    MultinomialNaiveBayes,
    NaiveBayes,
    NameAlias,
    NameRange,
    NameRef,
    NamespaceImport,
    NeuralNetwork,
    NeuralNetworkActivation,
    # node
    Node,
    NodeInput,
    NodeOutput,
    # model
    OMLEModel,
    OneClassSVM,
    OutlierValuePolicy,
    OutputBinding,
    OutputRole,
    OutputSpec,
    PostTransform,
    # predicate
    Predicate,
    PrototypeClustering,
    # core
    Scalar,
    ScorePolarity,
    SimplePredicate,
    SimplePredicateOperator,
    SimpleSetOperator,
    SimpleSetPredicate,
    SourceFramework,
    SparseTensor,
    SVMKernelType,
    SVMMulticlassStrategy,
    Target,
    TargetKind,
    TaskType,
    Tensor,
    TensorEntry,
    TensorRef,
    TensorType,
    TensorValue,
    Tree,
    TreeAggregation,
    TreeEnsemble,
    TreeNodeKind,
    TreeSplitOp,
    TruePredicate,
    # domain
    ValueDomain,
    ValueProperty,
)

# Validation
from .validation import (
    ValidationError,
    ValidationResult,
    assert_valid,
    validate,
)


def export_omle(model, path, **kwargs) -> None:
    """Export *model* to an OMLE file at *path*.

    If *model* is already an ``OMLEModel`` it is saved directly without
    requiring ``omle-convert``. Otherwise it is converted first — install
    the converter package with ``pip install omle-convert`` if needed.
    """
    if isinstance(model, OMLEModel):
        save(model, path)
        return
    try:
        from omle_convert import export_omle as _export
    except ImportError:
        raise ImportError(
            "omle-convert is required to convert models. "
            "Install it with: pip install omle-convert"
        ) from None
    _export(model, path, **kwargs)


def to_omle(model, **kwargs):
    """Convert a model to OMLE format.

    Delegates to ``omle_convert.to_omle``. Install the converter package
    with ``pip install omle-convert`` if it is not already available.
    """
    try:
        from omle_convert import to_omle as _convert
    except ImportError:
        raise ImportError(
            "omle-convert is required to convert models. "
            "Install it with: pip install omle-convert"
        ) from None
    return _convert(model, **kwargs)

try:
    from ._version import (
        __version__,  # generated by setuptools-scm at build time
    )
except ImportError:  # pragma: no cover - source checkout without a build
    __version__ = "0.0.0+unknown"

__all__ = [
    # enums
    "DataType", "MeasureLevel", "OutputRole", "PostTransform",
    "MissingValuePolicy", "InvalidValuePolicy", "OutlierValuePolicy",
    "TargetKind", "IntervalClosure", "ValueProperty",
    "SimplePredicateOperator", "SimpleSetOperator", "BooleanOperator",
    "TreeNodeKind", "TreeSplitOp", "TreeAggregation",
    "DistanceMeasure", "CovarianceType",
    "TaskType", "SVMKernelType", "SVMMulticlassStrategy", "NeuralNetworkActivation",
    # core
    "Scalar", "TensorType", "TensorRef", "TensorValue", "NameRef", "Tensor", "SparseTensor", "CSRMatrix", "TensorEntry",
    # metadata
    "ModelMetadata", "NamespaceImport",
    # interface
    "InputSpec", "OutputSpec", "OutputBinding",
    # domain
    "ValueDomain", "ContinuousDomain", "DiscreteDomain", "Interval", "DomainValue",
    # schema
    "ModelSchema", "Feature", "Target", "NameRange",
    # expression
    "Expression", "Apply",
    # predicate
    "Predicate", "TruePredicate", "FalsePredicate",
    "SimplePredicate", "SimpleSetPredicate", "CompoundPredicate",
    # node
    "Node", "NodeInput", "NodeOutput", "NameAlias", "CompositeNode", "Attribute",
    # function
    "DefineFunction", "FunctionParameter",
    # bodies
    "Linear", "NaiveBayes", "GaussianNaiveBayes", "MultinomialNaiveBayes",
    "BernoulliNaiveBayes", "CategoricalNaiveBayes",
    "Tree", "TreeEnsemble", "ComplexPredicate",
    "Clustering", "PrototypeClustering", "GaussianMixtureClustering",
    "LinearSVM", "KernelSVM", "SVM",
    "DenseLayer", "NeuralNetwork",
    # model
    "OMLEModel",
    # conversion
    "to_omle",
    "export_omle",
    # io
    "load", "save", "load_json", "save_json", "to_json", "from_json",
    "load_proto", "save_proto", "to_proto_bytes", "from_proto_bytes",
    # validation
    "validate", "assert_valid", "ValidationResult", "ValidationError",
]
